"use strict";

const { ANSI_DEFINITIONS: ANSI } = require("../definitions");

// Build a map of all possible ANSI sequences
const ANSI_SEQUENCES = new Map();

ANSI_SEQUENCES.set("|n", ANSI.RESET);
ANSI_SEQUENCES.set("|u", ANSI.UNDERLINE);

ANSI_SEQUENCES.set("|h", ANSI.HILITE);
ANSI_SEQUENCES.set("|H", ANSI.UNHILITE);

ANSI_SEQUENCES.set("|x", ANSI.HILITE + ANSI.BLACK);
ANSI_SEQUENCES.set("|r", ANSI.HILITE + ANSI.RED);
ANSI_SEQUENCES.set("|g", ANSI.HILITE + ANSI.GREEN);
ANSI_SEQUENCES.set("|y", ANSI.HILITE + ANSI.YELLOW);
ANSI_SEQUENCES.set("|b", ANSI.HILITE + ANSI.BLUE);
ANSI_SEQUENCES.set("|m", ANSI.HILITE + ANSI.MAGENTA);
ANSI_SEQUENCES.set("|c", ANSI.HILITE + ANSI.CYAN);
ANSI_SEQUENCES.set("|w", ANSI.HILITE + ANSI.WHITE);

ANSI_SEQUENCES.set("|X", ANSI.UNHILITE + ANSI.BLACK);
ANSI_SEQUENCES.set("|R", ANSI.UNHILITE + ANSI.RED);
ANSI_SEQUENCES.set("|G", ANSI.UNHILITE + ANSI.GREEN);
ANSI_SEQUENCES.set("|Y", ANSI.UNHILITE + ANSI.YELLOW);
ANSI_SEQUENCES.set("|B", ANSI.UNHILITE + ANSI.BLUE);
ANSI_SEQUENCES.set("|M", ANSI.UNHILITE + ANSI.MAGENTA);
ANSI_SEQUENCES.set("|C", ANSI.UNHILITE + ANSI.CYAN);
ANSI_SEQUENCES.set("|W", ANSI.UNHILITE + ANSI.WHITE);

ANSI_SEQUENCES.set("|[X", ANSI.BACK_BLACK);
ANSI_SEQUENCES.set("|[R", ANSI.BACK_RED);
ANSI_SEQUENCES.set("|[G", ANSI.BACK_GREEN);
ANSI_SEQUENCES.set("|[Y", ANSI.BACK_YELLOW);
ANSI_SEQUENCES.set("|[B", ANSI.BACK_BLUE);
ANSI_SEQUENCES.set("|[M", ANSI.BACK_MAGENTA);
ANSI_SEQUENCES.set("|[C", ANSI.BACK_CYAN);
ANSI_SEQUENCES.set("|[W", ANSI.BACK_WHITE);

// ANSI Matcher
const ANSI_REGEX = new RegExp(
  `(${[...ANSI_SEQUENCES.keys()]
    .map(k => "\\" + k.replace("[", "\\["))
    .join("|")})`,
  "g"
);

module.exports = {
  ANSI_SEQUENCES,
  ANSI_REGEX
};
